// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: AccountDataEnd.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface AccountDataEnd {
  accountName?: string | undefined;
}

function createBaseAccountDataEnd(): AccountDataEnd {
  return { accountName: undefined };
}

export const AccountDataEnd: MessageFns<AccountDataEnd> = {
  encode(message: AccountDataEnd, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accountName !== undefined) {
      writer.uint32(10).string(message.accountName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountDataEnd {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountDataEnd();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accountName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountDataEnd {
    return { accountName: isSet(object.accountName) ? globalThis.String(object.accountName) : undefined };
  },

  toJSON(message: AccountDataEnd): unknown {
    const obj: any = {};
    if (message.accountName !== undefined) {
      obj.accountName = message.accountName;
    }
    return obj;
  },

  create(base?: DeepPartial<AccountDataEnd>): AccountDataEnd {
    return AccountDataEnd.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AccountDataEnd>): AccountDataEnd {
    const message = createBaseAccountDataEnd();
    message.accountName = object.accountName ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
