// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: AccountDataRequest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface AccountDataRequest {
  subscribe?: boolean | undefined;
  acctCode?: string | undefined;
}

function createBaseAccountDataRequest(): AccountDataRequest {
  return { subscribe: undefined, acctCode: undefined };
}

export const AccountDataRequest: MessageFns<AccountDataRequest> = {
  encode(message: AccountDataRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subscribe !== undefined) {
      writer.uint32(8).bool(message.subscribe);
    }
    if (message.acctCode !== undefined) {
      writer.uint32(18).string(message.acctCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountDataRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountDataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.subscribe = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.acctCode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountDataRequest {
    return {
      subscribe: isSet(object.subscribe) ? globalThis.Boolean(object.subscribe) : undefined,
      acctCode: isSet(object.acctCode) ? globalThis.String(object.acctCode) : undefined,
    };
  },

  toJSON(message: AccountDataRequest): unknown {
    const obj: any = {};
    if (message.subscribe !== undefined) {
      obj.subscribe = message.subscribe;
    }
    if (message.acctCode !== undefined) {
      obj.acctCode = message.acctCode;
    }
    return obj;
  },

  create(base?: DeepPartial<AccountDataRequest>): AccountDataRequest {
    return AccountDataRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AccountDataRequest>): AccountDataRequest {
    const message = createBaseAccountDataRequest();
    message.subscribe = object.subscribe ?? undefined;
    message.acctCode = object.acctCode ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
