// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: AccountValue.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface AccountValue {
  key?: string | undefined;
  value?: string | undefined;
  currency?: string | undefined;
  accountName?: string | undefined;
}

function createBaseAccountValue(): AccountValue {
  return { key: undefined, value: undefined, currency: undefined, accountName: undefined };
}

export const AccountValue: MessageFns<AccountValue> = {
  encode(message: AccountValue, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== undefined) {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      writer.uint32(18).string(message.value);
    }
    if (message.currency !== undefined) {
      writer.uint32(26).string(message.currency);
    }
    if (message.accountName !== undefined) {
      writer.uint32(34).string(message.accountName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountValue {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountValue();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.accountName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountValue {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : undefined,
      value: isSet(object.value) ? globalThis.String(object.value) : undefined,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : undefined,
      accountName: isSet(object.accountName) ? globalThis.String(object.accountName) : undefined,
    };
  },

  toJSON(message: AccountValue): unknown {
    const obj: any = {};
    if (message.key !== undefined) {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    if (message.currency !== undefined) {
      obj.currency = message.currency;
    }
    if (message.accountName !== undefined) {
      obj.accountName = message.accountName;
    }
    return obj;
  },

  create(base?: DeepPartial<AccountValue>): AccountValue {
    return AccountValue.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AccountValue>): AccountValue {
    const message = createBaseAccountValue();
    message.key = object.key ?? undefined;
    message.value = object.value ?? undefined;
    message.currency = object.currency ?? undefined;
    message.accountName = object.accountName ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
