// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: AccountSummary.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface AccountSummary {
  reqId?: number | undefined;
  account?: string | undefined;
  tag?: string | undefined;
  value?: string | undefined;
  currency?: string | undefined;
}

function createBaseAccountSummary(): AccountSummary {
  return { reqId: undefined, account: undefined, tag: undefined, value: undefined, currency: undefined };
}

export const AccountSummary: MessageFns<AccountSummary> = {
  encode(message: AccountSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.account !== undefined) {
      writer.uint32(18).string(message.account);
    }
    if (message.tag !== undefined) {
      writer.uint32(26).string(message.tag);
    }
    if (message.value !== undefined) {
      writer.uint32(34).string(message.value);
    }
    if (message.currency !== undefined) {
      writer.uint32(42).string(message.currency);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.account = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.tag = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.value = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountSummary {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      account: isSet(object.account) ? globalThis.String(object.account) : undefined,
      tag: isSet(object.tag) ? globalThis.String(object.tag) : undefined,
      value: isSet(object.value) ? globalThis.String(object.value) : undefined,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : undefined,
    };
  },

  toJSON(message: AccountSummary): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.account !== undefined) {
      obj.account = message.account;
    }
    if (message.tag !== undefined) {
      obj.tag = message.tag;
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    if (message.currency !== undefined) {
      obj.currency = message.currency;
    }
    return obj;
  },

  create(base?: DeepPartial<AccountSummary>): AccountSummary {
    return AccountSummary.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AccountSummary>): AccountSummary {
    const message = createBaseAccountSummary();
    message.reqId = object.reqId ?? undefined;
    message.account = object.account ?? undefined;
    message.tag = object.tag ?? undefined;
    message.value = object.value ?? undefined;
    message.currency = object.currency ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
