// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: AllOpenOrdersRequest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

/** empty */
export interface AllOpenOrdersRequest {
}

function createBaseAllOpenOrdersRequest(): AllOpenOrdersRequest {
  return {};
}

export const AllOpenOrdersRequest: MessageFns<AllOpenOrdersRequest> = {
  encode(_: AllOpenOrdersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AllOpenOrdersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAllOpenOrdersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): AllOpenOrdersRequest {
    return {};
  },

  toJSON(_: AllOpenOrdersRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<AllOpenOrdersRequest>): AllOpenOrdersRequest {
    return AllOpenOrdersRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<AllOpenOrdersRequest>): AllOpenOrdersRequest {
    const message = createBaseAllOpenOrdersRequest();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
