// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: AutoOpenOrdersRequest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface AutoOpenOrdersRequest {
  autoBind?: boolean | undefined;
}

function createBaseAutoOpenOrdersRequest(): AutoOpenOrdersRequest {
  return { autoBind: undefined };
}

export const AutoOpenOrdersRequest: MessageFns<AutoOpenOrdersRequest> = {
  encode(message: AutoOpenOrdersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.autoBind !== undefined) {
      writer.uint32(8).bool(message.autoBind);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AutoOpenOrdersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAutoOpenOrdersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.autoBind = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AutoOpenOrdersRequest {
    return { autoBind: isSet(object.autoBind) ? globalThis.Boolean(object.autoBind) : undefined };
  },

  toJSON(message: AutoOpenOrdersRequest): unknown {
    const obj: any = {};
    if (message.autoBind !== undefined) {
      obj.autoBind = message.autoBind;
    }
    return obj;
  },

  create(base?: DeepPartial<AutoOpenOrdersRequest>): AutoOpenOrdersRequest {
    return AutoOpenOrdersRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AutoOpenOrdersRequest>): AutoOpenOrdersRequest {
    const message = createBaseAutoOpenOrdersRequest();
    message.autoBind = object.autoBind ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
