// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: CompletedOrdersRequest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface CompletedOrdersRequest {
  apiOnly?: boolean | undefined;
}

function createBaseCompletedOrdersRequest(): CompletedOrdersRequest {
  return { apiOnly: undefined };
}

export const CompletedOrdersRequest: MessageFns<CompletedOrdersRequest> = {
  encode(message: CompletedOrdersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.apiOnly !== undefined) {
      writer.uint32(8).bool(message.apiOnly);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompletedOrdersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompletedOrdersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.apiOnly = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CompletedOrdersRequest {
    return { apiOnly: isSet(object.apiOnly) ? globalThis.Boolean(object.apiOnly) : undefined };
  },

  toJSON(message: CompletedOrdersRequest): unknown {
    const obj: any = {};
    if (message.apiOnly !== undefined) {
      obj.apiOnly = message.apiOnly;
    }
    return obj;
  },

  create(base?: DeepPartial<CompletedOrdersRequest>): CompletedOrdersRequest {
    return CompletedOrdersRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CompletedOrdersRequest>): CompletedOrdersRequest {
    const message = createBaseCompletedOrdersRequest();
    message.apiOnly = object.apiOnly ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
