// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: ContractDescription.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Contract } from "./Contract";

export const protobufPackage = "protobuf";

export interface ContractDescription {
  contract?: Contract | undefined;
  derivativeSecTypes: string[];
}

function createBaseContractDescription(): ContractDescription {
  return { contract: undefined, derivativeSecTypes: [] };
}

export const ContractDescription: MessageFns<ContractDescription> = {
  encode(message: ContractDescription, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.contract !== undefined) {
      Contract.encode(message.contract, writer.uint32(10).fork()).join();
    }
    for (const v of message.derivativeSecTypes) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ContractDescription {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseContractDescription();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.contract = Contract.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.derivativeSecTypes.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ContractDescription {
    return {
      contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
      derivativeSecTypes: globalThis.Array.isArray(object?.derivativeSecTypes)
        ? object.derivativeSecTypes.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: ContractDescription): unknown {
    const obj: any = {};
    if (message.contract !== undefined) {
      obj.contract = Contract.toJSON(message.contract);
    }
    if (message.derivativeSecTypes?.length) {
      obj.derivativeSecTypes = message.derivativeSecTypes;
    }
    return obj;
  },

  create(base?: DeepPartial<ContractDescription>): ContractDescription {
    return ContractDescription.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ContractDescription>): ContractDescription {
    const message = createBaseContractDescription();
    message.contract = (object.contract !== undefined && object.contract !== null)
      ? Contract.fromPartial(object.contract)
      : undefined;
    message.derivativeSecTypes = object.derivativeSecTypes?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
