// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: CurrentTimeInMillis.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface CurrentTimeInMillis {
  currentTimeInMillis?: number | undefined;
}

function createBaseCurrentTimeInMillis(): CurrentTimeInMillis {
  return { currentTimeInMillis: undefined };
}

export const CurrentTimeInMillis: MessageFns<CurrentTimeInMillis> = {
  encode(message: CurrentTimeInMillis, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.currentTimeInMillis !== undefined) {
      writer.uint32(8).int64(message.currentTimeInMillis);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CurrentTimeInMillis {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCurrentTimeInMillis();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.currentTimeInMillis = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CurrentTimeInMillis {
    return {
      currentTimeInMillis: isSet(object.currentTimeInMillis)
        ? globalThis.Number(object.currentTimeInMillis)
        : undefined,
    };
  },

  toJSON(message: CurrentTimeInMillis): unknown {
    const obj: any = {};
    if (message.currentTimeInMillis !== undefined) {
      obj.currentTimeInMillis = Math.round(message.currentTimeInMillis);
    }
    return obj;
  },

  create(base?: DeepPartial<CurrentTimeInMillis>): CurrentTimeInMillis {
    return CurrentTimeInMillis.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CurrentTimeInMillis>): CurrentTimeInMillis {
    const message = createBaseCurrentTimeInMillis();
    message.currentTimeInMillis = object.currentTimeInMillis ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
