// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: DeltaNeutralContract.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface DeltaNeutralContract {
  conId?: number | undefined;
  delta?: number | undefined;
  price?: number | undefined;
}

function createBaseDeltaNeutralContract(): DeltaNeutralContract {
  return { conId: undefined, delta: undefined, price: undefined };
}

export const DeltaNeutralContract: MessageFns<DeltaNeutralContract> = {
  encode(message: DeltaNeutralContract, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conId !== undefined) {
      writer.uint32(8).int32(message.conId);
    }
    if (message.delta !== undefined) {
      writer.uint32(17).double(message.delta);
    }
    if (message.price !== undefined) {
      writer.uint32(25).double(message.price);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeltaNeutralContract {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeltaNeutralContract();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.conId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.delta = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.price = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeltaNeutralContract {
    return {
      conId: isSet(object.conId) ? globalThis.Number(object.conId) : undefined,
      delta: isSet(object.delta) ? globalThis.Number(object.delta) : undefined,
      price: isSet(object.price) ? globalThis.Number(object.price) : undefined,
    };
  },

  toJSON(message: DeltaNeutralContract): unknown {
    const obj: any = {};
    if (message.conId !== undefined) {
      obj.conId = Math.round(message.conId);
    }
    if (message.delta !== undefined) {
      obj.delta = message.delta;
    }
    if (message.price !== undefined) {
      obj.price = message.price;
    }
    return obj;
  },

  create(base?: DeepPartial<DeltaNeutralContract>): DeltaNeutralContract {
    return DeltaNeutralContract.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeltaNeutralContract>): DeltaNeutralContract {
    const message = createBaseDeltaNeutralContract();
    message.conId = object.conId ?? undefined;
    message.delta = object.delta ?? undefined;
    message.price = object.price ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
