// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: ExecutionRequest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ExecutionFilter } from "./ExecutionFilter";

export const protobufPackage = "protobuf";

export interface ExecutionRequest {
  reqId?: number | undefined;
  executionFilter?: ExecutionFilter | undefined;
}

function createBaseExecutionRequest(): ExecutionRequest {
  return { reqId: undefined, executionFilter: undefined };
}

export const ExecutionRequest: MessageFns<ExecutionRequest> = {
  encode(message: ExecutionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.executionFilter !== undefined) {
      ExecutionFilter.encode(message.executionFilter, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecutionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecutionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.executionFilter = ExecutionFilter.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecutionRequest {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      executionFilter: isSet(object.executionFilter) ? ExecutionFilter.fromJSON(object.executionFilter) : undefined,
    };
  },

  toJSON(message: ExecutionRequest): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.executionFilter !== undefined) {
      obj.executionFilter = ExecutionFilter.toJSON(message.executionFilter);
    }
    return obj;
  },

  create(base?: DeepPartial<ExecutionRequest>): ExecutionRequest {
    return ExecutionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ExecutionRequest>): ExecutionRequest {
    const message = createBaseExecutionRequest();
    message.reqId = object.reqId ?? undefined;
    message.executionFilter = (object.executionFilter !== undefined && object.executionFilter !== null)
      ? ExecutionFilter.fromPartial(object.executionFilter)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
