// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: FamilyCodes.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { FamilyCode } from "./FamilyCode";

export const protobufPackage = "protobuf";

export interface FamilyCodes {
  familyCodes: FamilyCode[];
}

function createBaseFamilyCodes(): FamilyCodes {
  return { familyCodes: [] };
}

export const FamilyCodes: MessageFns<FamilyCodes> = {
  encode(message: FamilyCodes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.familyCodes) {
      FamilyCode.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FamilyCodes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFamilyCodes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.familyCodes.push(FamilyCode.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FamilyCodes {
    return {
      familyCodes: globalThis.Array.isArray(object?.familyCodes)
        ? object.familyCodes.map((e: any) => FamilyCode.fromJSON(e))
        : [],
    };
  },

  toJSON(message: FamilyCodes): unknown {
    const obj: any = {};
    if (message.familyCodes?.length) {
      obj.familyCodes = message.familyCodes.map((e) => FamilyCode.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<FamilyCodes>): FamilyCodes {
    return FamilyCodes.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FamilyCodes>): FamilyCodes {
    const message = createBaseFamilyCodes();
    message.familyCodes = object.familyCodes?.map((e) => FamilyCode.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
