// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: FARequest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface FARequest {
  faDataType?: number | undefined;
}

function createBaseFARequest(): FARequest {
  return { faDataType: undefined };
}

export const FARequest: MessageFns<FARequest> = {
  encode(message: FARequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.faDataType !== undefined) {
      writer.uint32(8).int32(message.faDataType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FARequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFARequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.faDataType = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FARequest {
    return { faDataType: isSet(object.faDataType) ? globalThis.Number(object.faDataType) : undefined };
  },

  toJSON(message: FARequest): unknown {
    const obj: any = {};
    if (message.faDataType !== undefined) {
      obj.faDataType = Math.round(message.faDataType);
    }
    return obj;
  },

  create(base?: DeepPartial<FARequest>): FARequest {
    return FARequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FARequest>): FARequest {
    const message = createBaseFARequest();
    message.faDataType = object.faDataType ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
