// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: HistoricalNewsEnd.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface HistoricalNewsEnd {
  reqId?: number | undefined;
  hasMore?: boolean | undefined;
}

function createBaseHistoricalNewsEnd(): HistoricalNewsEnd {
  return { reqId: undefined, hasMore: undefined };
}

export const HistoricalNewsEnd: MessageFns<HistoricalNewsEnd> = {
  encode(message: HistoricalNewsEnd, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.hasMore !== undefined) {
      writer.uint32(16).bool(message.hasMore);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HistoricalNewsEnd {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHistoricalNewsEnd();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.hasMore = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HistoricalNewsEnd {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      hasMore: isSet(object.hasMore) ? globalThis.Boolean(object.hasMore) : undefined,
    };
  },

  toJSON(message: HistoricalNewsEnd): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.hasMore !== undefined) {
      obj.hasMore = message.hasMore;
    }
    return obj;
  },

  create(base?: DeepPartial<HistoricalNewsEnd>): HistoricalNewsEnd {
    return HistoricalNewsEnd.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HistoricalNewsEnd>): HistoricalNewsEnd {
    const message = createBaseHistoricalNewsEnd();
    message.reqId = object.reqId ?? undefined;
    message.hasMore = object.hasMore ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
