// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: HistoricalSession.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface HistoricalSession {
  startDateTime?: string | undefined;
  endDateTime?: string | undefined;
  refDate?: string | undefined;
}

function createBaseHistoricalSession(): HistoricalSession {
  return { startDateTime: undefined, endDateTime: undefined, refDate: undefined };
}

export const HistoricalSession: MessageFns<HistoricalSession> = {
  encode(message: HistoricalSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.startDateTime !== undefined) {
      writer.uint32(10).string(message.startDateTime);
    }
    if (message.endDateTime !== undefined) {
      writer.uint32(18).string(message.endDateTime);
    }
    if (message.refDate !== undefined) {
      writer.uint32(26).string(message.refDate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HistoricalSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHistoricalSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.startDateTime = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.endDateTime = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.refDate = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HistoricalSession {
    return {
      startDateTime: isSet(object.startDateTime) ? globalThis.String(object.startDateTime) : undefined,
      endDateTime: isSet(object.endDateTime) ? globalThis.String(object.endDateTime) : undefined,
      refDate: isSet(object.refDate) ? globalThis.String(object.refDate) : undefined,
    };
  },

  toJSON(message: HistoricalSession): unknown {
    const obj: any = {};
    if (message.startDateTime !== undefined) {
      obj.startDateTime = message.startDateTime;
    }
    if (message.endDateTime !== undefined) {
      obj.endDateTime = message.endDateTime;
    }
    if (message.refDate !== undefined) {
      obj.refDate = message.refDate;
    }
    return obj;
  },

  create(base?: DeepPartial<HistoricalSession>): HistoricalSession {
    return HistoricalSession.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HistoricalSession>): HistoricalSession {
    const message = createBaseHistoricalSession();
    message.startDateTime = object.startDateTime ?? undefined;
    message.endDateTime = object.endDateTime ?? undefined;
    message.refDate = object.refDate ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
