// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: HistogramDataRequest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Contract } from "./Contract";

export const protobufPackage = "protobuf";

export interface HistogramDataRequest {
  reqId?: number | undefined;
  contract?: Contract | undefined;
  useRTH?: boolean | undefined;
  timePeriod?: string | undefined;
}

function createBaseHistogramDataRequest(): HistogramDataRequest {
  return { reqId: undefined, contract: undefined, useRTH: undefined, timePeriod: undefined };
}

export const HistogramDataRequest: MessageFns<HistogramDataRequest> = {
  encode(message: HistogramDataRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.contract !== undefined) {
      Contract.encode(message.contract, writer.uint32(18).fork()).join();
    }
    if (message.useRTH !== undefined) {
      writer.uint32(24).bool(message.useRTH);
    }
    if (message.timePeriod !== undefined) {
      writer.uint32(34).string(message.timePeriod);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HistogramDataRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHistogramDataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.contract = Contract.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.useRTH = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.timePeriod = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HistogramDataRequest {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
      useRTH: isSet(object.useRTH) ? globalThis.Boolean(object.useRTH) : undefined,
      timePeriod: isSet(object.timePeriod) ? globalThis.String(object.timePeriod) : undefined,
    };
  },

  toJSON(message: HistogramDataRequest): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.contract !== undefined) {
      obj.contract = Contract.toJSON(message.contract);
    }
    if (message.useRTH !== undefined) {
      obj.useRTH = message.useRTH;
    }
    if (message.timePeriod !== undefined) {
      obj.timePeriod = message.timePeriod;
    }
    return obj;
  },

  create(base?: DeepPartial<HistogramDataRequest>): HistogramDataRequest {
    return HistogramDataRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HistogramDataRequest>): HistogramDataRequest {
    const message = createBaseHistogramDataRequest();
    message.reqId = object.reqId ?? undefined;
    message.contract = (object.contract !== undefined && object.contract !== null)
      ? Contract.fromPartial(object.contract)
      : undefined;
    message.useRTH = object.useRTH ?? undefined;
    message.timePeriod = object.timePeriod ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
