// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: HistoricalSchedule.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { HistoricalSession } from "./HistoricalSession";

export const protobufPackage = "protobuf";

export interface HistoricalSchedule {
  reqId?: number | undefined;
  startDateTime?: string | undefined;
  endDateTime?: string | undefined;
  timeZone?: string | undefined;
  historicalSessions: HistoricalSession[];
}

function createBaseHistoricalSchedule(): HistoricalSchedule {
  return {
    reqId: undefined,
    startDateTime: undefined,
    endDateTime: undefined,
    timeZone: undefined,
    historicalSessions: [],
  };
}

export const HistoricalSchedule: MessageFns<HistoricalSchedule> = {
  encode(message: HistoricalSchedule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.startDateTime !== undefined) {
      writer.uint32(18).string(message.startDateTime);
    }
    if (message.endDateTime !== undefined) {
      writer.uint32(26).string(message.endDateTime);
    }
    if (message.timeZone !== undefined) {
      writer.uint32(34).string(message.timeZone);
    }
    for (const v of message.historicalSessions) {
      HistoricalSession.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HistoricalSchedule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHistoricalSchedule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.startDateTime = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.endDateTime = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.timeZone = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.historicalSessions.push(HistoricalSession.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HistoricalSchedule {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      startDateTime: isSet(object.startDateTime) ? globalThis.String(object.startDateTime) : undefined,
      endDateTime: isSet(object.endDateTime) ? globalThis.String(object.endDateTime) : undefined,
      timeZone: isSet(object.timeZone) ? globalThis.String(object.timeZone) : undefined,
      historicalSessions: globalThis.Array.isArray(object?.historicalSessions)
        ? object.historicalSessions.map((e: any) => HistoricalSession.fromJSON(e))
        : [],
    };
  },

  toJSON(message: HistoricalSchedule): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.startDateTime !== undefined) {
      obj.startDateTime = message.startDateTime;
    }
    if (message.endDateTime !== undefined) {
      obj.endDateTime = message.endDateTime;
    }
    if (message.timeZone !== undefined) {
      obj.timeZone = message.timeZone;
    }
    if (message.historicalSessions?.length) {
      obj.historicalSessions = message.historicalSessions.map((e) => HistoricalSession.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<HistoricalSchedule>): HistoricalSchedule {
    return HistoricalSchedule.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HistoricalSchedule>): HistoricalSchedule {
    const message = createBaseHistoricalSchedule();
    message.reqId = object.reqId ?? undefined;
    message.startDateTime = object.startDateTime ?? undefined;
    message.endDateTime = object.endDateTime ?? undefined;
    message.timeZone = object.timeZone ?? undefined;
    message.historicalSessions = object.historicalSessions?.map((e) => HistoricalSession.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
