// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: MarketDepthRequest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Contract } from "./Contract";

export const protobufPackage = "protobuf";

export interface MarketDepthRequest {
  reqId?: number | undefined;
  contract?: Contract | undefined;
  numRows?: number | undefined;
  isSmartDepth?: boolean | undefined;
  marketDepthOptions: { [key: string]: string };
}

export interface MarketDepthRequest_MarketDepthOptionsEntry {
  key: string;
  value: string;
}

function createBaseMarketDepthRequest(): MarketDepthRequest {
  return { reqId: undefined, contract: undefined, numRows: undefined, isSmartDepth: undefined, marketDepthOptions: {} };
}

export const MarketDepthRequest: MessageFns<MarketDepthRequest> = {
  encode(message: MarketDepthRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.contract !== undefined) {
      Contract.encode(message.contract, writer.uint32(18).fork()).join();
    }
    if (message.numRows !== undefined) {
      writer.uint32(24).int32(message.numRows);
    }
    if (message.isSmartDepth !== undefined) {
      writer.uint32(32).bool(message.isSmartDepth);
    }
    globalThis.Object.entries(message.marketDepthOptions).forEach(([key, value]: [string, string]) => {
      MarketDepthRequest_MarketDepthOptionsEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketDepthRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketDepthRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.contract = Contract.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.numRows = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isSmartDepth = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = MarketDepthRequest_MarketDepthOptionsEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.marketDepthOptions[entry5.key] = entry5.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketDepthRequest {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
      numRows: isSet(object.numRows) ? globalThis.Number(object.numRows) : undefined,
      isSmartDepth: isSet(object.isSmartDepth) ? globalThis.Boolean(object.isSmartDepth) : undefined,
      marketDepthOptions: isObject(object.marketDepthOptions)
        ? (globalThis.Object.entries(object.marketDepthOptions) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: MarketDepthRequest): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.contract !== undefined) {
      obj.contract = Contract.toJSON(message.contract);
    }
    if (message.numRows !== undefined) {
      obj.numRows = Math.round(message.numRows);
    }
    if (message.isSmartDepth !== undefined) {
      obj.isSmartDepth = message.isSmartDepth;
    }
    if (message.marketDepthOptions) {
      const entries = globalThis.Object.entries(message.marketDepthOptions) as [string, string][];
      if (entries.length > 0) {
        obj.marketDepthOptions = {};
        entries.forEach(([k, v]) => {
          obj.marketDepthOptions[k] = v;
        });
      }
    }
    return obj;
  },

  create(base?: DeepPartial<MarketDepthRequest>): MarketDepthRequest {
    return MarketDepthRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MarketDepthRequest>): MarketDepthRequest {
    const message = createBaseMarketDepthRequest();
    message.reqId = object.reqId ?? undefined;
    message.contract = (object.contract !== undefined && object.contract !== null)
      ? Contract.fromPartial(object.contract)
      : undefined;
    message.numRows = object.numRows ?? undefined;
    message.isSmartDepth = object.isSmartDepth ?? undefined;
    message.marketDepthOptions = (globalThis.Object.entries(object.marketDepthOptions ?? {}) as [string, string][])
      .reduce((acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      }, {});
    return message;
  },
};

function createBaseMarketDepthRequest_MarketDepthOptionsEntry(): MarketDepthRequest_MarketDepthOptionsEntry {
  return { key: "", value: "" };
}

export const MarketDepthRequest_MarketDepthOptionsEntry: MessageFns<MarketDepthRequest_MarketDepthOptionsEntry> = {
  encode(message: MarketDepthRequest_MarketDepthOptionsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketDepthRequest_MarketDepthOptionsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketDepthRequest_MarketDepthOptionsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketDepthRequest_MarketDepthOptionsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: MarketDepthRequest_MarketDepthOptionsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<MarketDepthRequest_MarketDepthOptionsEntry>): MarketDepthRequest_MarketDepthOptionsEntry {
    return MarketDepthRequest_MarketDepthOptionsEntry.fromPartial(base ?? {});
  },
  fromPartial(
    object: DeepPartial<MarketDepthRequest_MarketDepthOptionsEntry>,
  ): MarketDepthRequest_MarketDepthOptionsEntry {
    const message = createBaseMarketDepthRequest_MarketDepthOptionsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
