// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: MarketDataRequest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Contract } from "./Contract";

export const protobufPackage = "protobuf";

export interface MarketDataRequest {
  reqId?: number | undefined;
  contract?: Contract | undefined;
  genericTickList?: string | undefined;
  snapshot?: boolean | undefined;
  regulatorySnapshot?: boolean | undefined;
  marketDataOptions: { [key: string]: string };
}

export interface MarketDataRequest_MarketDataOptionsEntry {
  key: string;
  value: string;
}

function createBaseMarketDataRequest(): MarketDataRequest {
  return {
    reqId: undefined,
    contract: undefined,
    genericTickList: undefined,
    snapshot: undefined,
    regulatorySnapshot: undefined,
    marketDataOptions: {},
  };
}

export const MarketDataRequest: MessageFns<MarketDataRequest> = {
  encode(message: MarketDataRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.contract !== undefined) {
      Contract.encode(message.contract, writer.uint32(18).fork()).join();
    }
    if (message.genericTickList !== undefined) {
      writer.uint32(26).string(message.genericTickList);
    }
    if (message.snapshot !== undefined) {
      writer.uint32(32).bool(message.snapshot);
    }
    if (message.regulatorySnapshot !== undefined) {
      writer.uint32(40).bool(message.regulatorySnapshot);
    }
    globalThis.Object.entries(message.marketDataOptions).forEach(([key, value]: [string, string]) => {
      MarketDataRequest_MarketDataOptionsEntry.encode({ key: key as any, value }, writer.uint32(50).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketDataRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketDataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.contract = Contract.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.genericTickList = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.snapshot = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.regulatorySnapshot = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const entry6 = MarketDataRequest_MarketDataOptionsEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.marketDataOptions[entry6.key] = entry6.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketDataRequest {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
      genericTickList: isSet(object.genericTickList) ? globalThis.String(object.genericTickList) : undefined,
      snapshot: isSet(object.snapshot) ? globalThis.Boolean(object.snapshot) : undefined,
      regulatorySnapshot: isSet(object.regulatorySnapshot) ? globalThis.Boolean(object.regulatorySnapshot) : undefined,
      marketDataOptions: isObject(object.marketDataOptions)
        ? (globalThis.Object.entries(object.marketDataOptions) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: MarketDataRequest): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.contract !== undefined) {
      obj.contract = Contract.toJSON(message.contract);
    }
    if (message.genericTickList !== undefined) {
      obj.genericTickList = message.genericTickList;
    }
    if (message.snapshot !== undefined) {
      obj.snapshot = message.snapshot;
    }
    if (message.regulatorySnapshot !== undefined) {
      obj.regulatorySnapshot = message.regulatorySnapshot;
    }
    if (message.marketDataOptions) {
      const entries = globalThis.Object.entries(message.marketDataOptions) as [string, string][];
      if (entries.length > 0) {
        obj.marketDataOptions = {};
        entries.forEach(([k, v]) => {
          obj.marketDataOptions[k] = v;
        });
      }
    }
    return obj;
  },

  create(base?: DeepPartial<MarketDataRequest>): MarketDataRequest {
    return MarketDataRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MarketDataRequest>): MarketDataRequest {
    const message = createBaseMarketDataRequest();
    message.reqId = object.reqId ?? undefined;
    message.contract = (object.contract !== undefined && object.contract !== null)
      ? Contract.fromPartial(object.contract)
      : undefined;
    message.genericTickList = object.genericTickList ?? undefined;
    message.snapshot = object.snapshot ?? undefined;
    message.regulatorySnapshot = object.regulatorySnapshot ?? undefined;
    message.marketDataOptions = (globalThis.Object.entries(object.marketDataOptions ?? {}) as [string, string][])
      .reduce((acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      }, {});
    return message;
  },
};

function createBaseMarketDataRequest_MarketDataOptionsEntry(): MarketDataRequest_MarketDataOptionsEntry {
  return { key: "", value: "" };
}

export const MarketDataRequest_MarketDataOptionsEntry: MessageFns<MarketDataRequest_MarketDataOptionsEntry> = {
  encode(message: MarketDataRequest_MarketDataOptionsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketDataRequest_MarketDataOptionsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketDataRequest_MarketDataOptionsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketDataRequest_MarketDataOptionsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: MarketDataRequest_MarketDataOptionsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<MarketDataRequest_MarketDataOptionsEntry>): MarketDataRequest_MarketDataOptionsEntry {
    return MarketDataRequest_MarketDataOptionsEntry.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MarketDataRequest_MarketDataOptionsEntry>): MarketDataRequest_MarketDataOptionsEntry {
    const message = createBaseMarketDataRequest_MarketDataOptionsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
