// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: MarketRuleRequest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface MarketRuleRequest {
  marketRuleId?: number | undefined;
}

function createBaseMarketRuleRequest(): MarketRuleRequest {
  return { marketRuleId: undefined };
}

export const MarketRuleRequest: MessageFns<MarketRuleRequest> = {
  encode(message: MarketRuleRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.marketRuleId !== undefined) {
      writer.uint32(8).int32(message.marketRuleId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketRuleRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketRuleRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.marketRuleId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketRuleRequest {
    return { marketRuleId: isSet(object.marketRuleId) ? globalThis.Number(object.marketRuleId) : undefined };
  },

  toJSON(message: MarketRuleRequest): unknown {
    const obj: any = {};
    if (message.marketRuleId !== undefined) {
      obj.marketRuleId = Math.round(message.marketRuleId);
    }
    return obj;
  },

  create(base?: DeepPartial<MarketRuleRequest>): MarketRuleRequest {
    return MarketRuleRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MarketRuleRequest>): MarketRuleRequest {
    const message = createBaseMarketRuleRequest();
    message.marketRuleId = object.marketRuleId ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
