// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: MarketDepth.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { MarketDepthData } from "./MarketDepthData";

export const protobufPackage = "protobuf";

export interface MarketDepth {
  reqId?: number | undefined;
  marketDepthData?: MarketDepthData | undefined;
}

function createBaseMarketDepth(): MarketDepth {
  return { reqId: undefined, marketDepthData: undefined };
}

export const MarketDepth: MessageFns<MarketDepth> = {
  encode(message: MarketDepth, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.marketDepthData !== undefined) {
      MarketDepthData.encode(message.marketDepthData, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketDepth {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketDepth();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.marketDepthData = MarketDepthData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketDepth {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      marketDepthData: isSet(object.marketDepthData) ? MarketDepthData.fromJSON(object.marketDepthData) : undefined,
    };
  },

  toJSON(message: MarketDepth): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.marketDepthData !== undefined) {
      obj.marketDepthData = MarketDepthData.toJSON(message.marketDepthData);
    }
    return obj;
  },

  create(base?: DeepPartial<MarketDepth>): MarketDepth {
    return MarketDepth.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MarketDepth>): MarketDepth {
    const message = createBaseMarketDepth();
    message.reqId = object.reqId ?? undefined;
    message.marketDepthData = (object.marketDepthData !== undefined && object.marketDepthData !== null)
      ? MarketDepthData.fromPartial(object.marketDepthData)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
