// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: MessageConfig.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface MessageConfig {
  id?: number | undefined;
  title?: string | undefined;
  message?: string | undefined;
  defaultAction?: string | undefined;
  enabled?: boolean | undefined;
}

function createBaseMessageConfig(): MessageConfig {
  return { id: undefined, title: undefined, message: undefined, defaultAction: undefined, enabled: undefined };
}

export const MessageConfig: MessageFns<MessageConfig> = {
  encode(message: MessageConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(8).int32(message.id);
    }
    if (message.title !== undefined) {
      writer.uint32(18).string(message.title);
    }
    if (message.message !== undefined) {
      writer.uint32(26).string(message.message);
    }
    if (message.defaultAction !== undefined) {
      writer.uint32(34).string(message.defaultAction);
    }
    if (message.enabled !== undefined) {
      writer.uint32(40).bool(message.enabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessageConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessageConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.defaultAction = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MessageConfig {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : undefined,
      title: isSet(object.title) ? globalThis.String(object.title) : undefined,
      message: isSet(object.message) ? globalThis.String(object.message) : undefined,
      defaultAction: isSet(object.defaultAction) ? globalThis.String(object.defaultAction) : undefined,
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : undefined,
    };
  },

  toJSON(message: MessageConfig): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = Math.round(message.id);
    }
    if (message.title !== undefined) {
      obj.title = message.title;
    }
    if (message.message !== undefined) {
      obj.message = message.message;
    }
    if (message.defaultAction !== undefined) {
      obj.defaultAction = message.defaultAction;
    }
    if (message.enabled !== undefined) {
      obj.enabled = message.enabled;
    }
    return obj;
  },

  create(base?: DeepPartial<MessageConfig>): MessageConfig {
    return MessageConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MessageConfig>): MessageConfig {
    const message = createBaseMessageConfig();
    message.id = object.id ?? undefined;
    message.title = object.title ?? undefined;
    message.message = object.message ?? undefined;
    message.defaultAction = object.defaultAction ?? undefined;
    message.enabled = object.enabled ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
