// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: NewsArticleRequest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface NewsArticleRequest {
  reqId?: number | undefined;
  providerCode?: string | undefined;
  articleId?: string | undefined;
  newsArticleOptions: { [key: string]: string };
}

export interface NewsArticleRequest_NewsArticleOptionsEntry {
  key: string;
  value: string;
}

function createBaseNewsArticleRequest(): NewsArticleRequest {
  return { reqId: undefined, providerCode: undefined, articleId: undefined, newsArticleOptions: {} };
}

export const NewsArticleRequest: MessageFns<NewsArticleRequest> = {
  encode(message: NewsArticleRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.providerCode !== undefined) {
      writer.uint32(18).string(message.providerCode);
    }
    if (message.articleId !== undefined) {
      writer.uint32(26).string(message.articleId);
    }
    globalThis.Object.entries(message.newsArticleOptions).forEach(([key, value]: [string, string]) => {
      NewsArticleRequest_NewsArticleOptionsEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NewsArticleRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNewsArticleRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.providerCode = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.articleId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = NewsArticleRequest_NewsArticleOptionsEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.newsArticleOptions[entry4.key] = entry4.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NewsArticleRequest {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      providerCode: isSet(object.providerCode) ? globalThis.String(object.providerCode) : undefined,
      articleId: isSet(object.articleId) ? globalThis.String(object.articleId) : undefined,
      newsArticleOptions: isObject(object.newsArticleOptions)
        ? (globalThis.Object.entries(object.newsArticleOptions) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: NewsArticleRequest): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.providerCode !== undefined) {
      obj.providerCode = message.providerCode;
    }
    if (message.articleId !== undefined) {
      obj.articleId = message.articleId;
    }
    if (message.newsArticleOptions) {
      const entries = globalThis.Object.entries(message.newsArticleOptions) as [string, string][];
      if (entries.length > 0) {
        obj.newsArticleOptions = {};
        entries.forEach(([k, v]) => {
          obj.newsArticleOptions[k] = v;
        });
      }
    }
    return obj;
  },

  create(base?: DeepPartial<NewsArticleRequest>): NewsArticleRequest {
    return NewsArticleRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<NewsArticleRequest>): NewsArticleRequest {
    const message = createBaseNewsArticleRequest();
    message.reqId = object.reqId ?? undefined;
    message.providerCode = object.providerCode ?? undefined;
    message.articleId = object.articleId ?? undefined;
    message.newsArticleOptions = (globalThis.Object.entries(object.newsArticleOptions ?? {}) as [string, string][])
      .reduce((acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      }, {});
    return message;
  },
};

function createBaseNewsArticleRequest_NewsArticleOptionsEntry(): NewsArticleRequest_NewsArticleOptionsEntry {
  return { key: "", value: "" };
}

export const NewsArticleRequest_NewsArticleOptionsEntry: MessageFns<NewsArticleRequest_NewsArticleOptionsEntry> = {
  encode(message: NewsArticleRequest_NewsArticleOptionsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NewsArticleRequest_NewsArticleOptionsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNewsArticleRequest_NewsArticleOptionsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NewsArticleRequest_NewsArticleOptionsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: NewsArticleRequest_NewsArticleOptionsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<NewsArticleRequest_NewsArticleOptionsEntry>): NewsArticleRequest_NewsArticleOptionsEntry {
    return NewsArticleRequest_NewsArticleOptionsEntry.fromPartial(base ?? {});
  },
  fromPartial(
    object: DeepPartial<NewsArticleRequest_NewsArticleOptionsEntry>,
  ): NewsArticleRequest_NewsArticleOptionsEntry {
    const message = createBaseNewsArticleRequest_NewsArticleOptionsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
