// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: PnLRequest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface PnLRequest {
  reqId?: number | undefined;
  account?: string | undefined;
  modelCode?: string | undefined;
}

function createBasePnLRequest(): PnLRequest {
  return { reqId: undefined, account: undefined, modelCode: undefined };
}

export const PnLRequest: MessageFns<PnLRequest> = {
  encode(message: PnLRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.account !== undefined) {
      writer.uint32(18).string(message.account);
    }
    if (message.modelCode !== undefined) {
      writer.uint32(26).string(message.modelCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PnLRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePnLRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.account = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.modelCode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PnLRequest {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      account: isSet(object.account) ? globalThis.String(object.account) : undefined,
      modelCode: isSet(object.modelCode) ? globalThis.String(object.modelCode) : undefined,
    };
  },

  toJSON(message: PnLRequest): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.account !== undefined) {
      obj.account = message.account;
    }
    if (message.modelCode !== undefined) {
      obj.modelCode = message.modelCode;
    }
    return obj;
  },

  create(base?: DeepPartial<PnLRequest>): PnLRequest {
    return PnLRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PnLRequest>): PnLRequest {
    const message = createBasePnLRequest();
    message.reqId = object.reqId ?? undefined;
    message.account = object.account ?? undefined;
    message.modelCode = object.modelCode ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
