// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: PositionMulti.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Contract } from "./Contract";

export const protobufPackage = "protobuf";

export interface PositionMulti {
  reqId?: number | undefined;
  account?: string | undefined;
  contract?: Contract | undefined;
  position?: string | undefined;
  avgCost?: number | undefined;
  modelCode?: string | undefined;
}

function createBasePositionMulti(): PositionMulti {
  return {
    reqId: undefined,
    account: undefined,
    contract: undefined,
    position: undefined,
    avgCost: undefined,
    modelCode: undefined,
  };
}

export const PositionMulti: MessageFns<PositionMulti> = {
  encode(message: PositionMulti, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.account !== undefined) {
      writer.uint32(18).string(message.account);
    }
    if (message.contract !== undefined) {
      Contract.encode(message.contract, writer.uint32(26).fork()).join();
    }
    if (message.position !== undefined) {
      writer.uint32(34).string(message.position);
    }
    if (message.avgCost !== undefined) {
      writer.uint32(41).double(message.avgCost);
    }
    if (message.modelCode !== undefined) {
      writer.uint32(50).string(message.modelCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PositionMulti {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePositionMulti();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.account = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contract = Contract.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.position = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.avgCost = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.modelCode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PositionMulti {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      account: isSet(object.account) ? globalThis.String(object.account) : undefined,
      contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
      position: isSet(object.position) ? globalThis.String(object.position) : undefined,
      avgCost: isSet(object.avgCost) ? globalThis.Number(object.avgCost) : undefined,
      modelCode: isSet(object.modelCode) ? globalThis.String(object.modelCode) : undefined,
    };
  },

  toJSON(message: PositionMulti): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.account !== undefined) {
      obj.account = message.account;
    }
    if (message.contract !== undefined) {
      obj.contract = Contract.toJSON(message.contract);
    }
    if (message.position !== undefined) {
      obj.position = message.position;
    }
    if (message.avgCost !== undefined) {
      obj.avgCost = message.avgCost;
    }
    if (message.modelCode !== undefined) {
      obj.modelCode = message.modelCode;
    }
    return obj;
  },

  create(base?: DeepPartial<PositionMulti>): PositionMulti {
    return PositionMulti.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PositionMulti>): PositionMulti {
    const message = createBasePositionMulti();
    message.reqId = object.reqId ?? undefined;
    message.account = object.account ?? undefined;
    message.contract = (object.contract !== undefined && object.contract !== null)
      ? Contract.fromPartial(object.contract)
      : undefined;
    message.position = object.position ?? undefined;
    message.avgCost = object.avgCost ?? undefined;
    message.modelCode = object.modelCode ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
