// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: RerouteMarketDataRequest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface RerouteMarketDataRequest {
  reqId?: number | undefined;
  conId?: number | undefined;
  exchange?: string | undefined;
}

function createBaseRerouteMarketDataRequest(): RerouteMarketDataRequest {
  return { reqId: undefined, conId: undefined, exchange: undefined };
}

export const RerouteMarketDataRequest: MessageFns<RerouteMarketDataRequest> = {
  encode(message: RerouteMarketDataRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.conId !== undefined) {
      writer.uint32(16).int32(message.conId);
    }
    if (message.exchange !== undefined) {
      writer.uint32(26).string(message.exchange);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RerouteMarketDataRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRerouteMarketDataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.conId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.exchange = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RerouteMarketDataRequest {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      conId: isSet(object.conId) ? globalThis.Number(object.conId) : undefined,
      exchange: isSet(object.exchange) ? globalThis.String(object.exchange) : undefined,
    };
  },

  toJSON(message: RerouteMarketDataRequest): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.conId !== undefined) {
      obj.conId = Math.round(message.conId);
    }
    if (message.exchange !== undefined) {
      obj.exchange = message.exchange;
    }
    return obj;
  },

  create(base?: DeepPartial<RerouteMarketDataRequest>): RerouteMarketDataRequest {
    return RerouteMarketDataRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RerouteMarketDataRequest>): RerouteMarketDataRequest {
    const message = createBaseRerouteMarketDataRequest();
    message.reqId = object.reqId ?? undefined;
    message.conId = object.conId ?? undefined;
    message.exchange = object.exchange ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
