// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: ScannerData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ScannerDataElement } from "./ScannerDataElement";

export const protobufPackage = "protobuf";

export interface ScannerData {
  reqId?: number | undefined;
  scannerDataElement: ScannerDataElement[];
}

function createBaseScannerData(): ScannerData {
  return { reqId: undefined, scannerDataElement: [] };
}

export const ScannerData: MessageFns<ScannerData> = {
  encode(message: ScannerData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    for (const v of message.scannerDataElement) {
      ScannerDataElement.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScannerData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScannerData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.scannerDataElement.push(ScannerDataElement.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScannerData {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      scannerDataElement: globalThis.Array.isArray(object?.scannerDataElement)
        ? object.scannerDataElement.map((e: any) => ScannerDataElement.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ScannerData): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.scannerDataElement?.length) {
      obj.scannerDataElement = message.scannerDataElement.map((e) => ScannerDataElement.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ScannerData>): ScannerData {
    return ScannerData.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ScannerData>): ScannerData {
    const message = createBaseScannerData();
    message.reqId = object.reqId ?? undefined;
    message.scannerDataElement = object.scannerDataElement?.map((e) => ScannerDataElement.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
