// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: SecDefOptParameter.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface SecDefOptParameter {
  reqId?: number | undefined;
  exchange?: string | undefined;
  underlyingConId?: number | undefined;
  tradingClass?: string | undefined;
  multiplier?: string | undefined;
  expirations: string[];
  strikes: number[];
}

function createBaseSecDefOptParameter(): SecDefOptParameter {
  return {
    reqId: undefined,
    exchange: undefined,
    underlyingConId: undefined,
    tradingClass: undefined,
    multiplier: undefined,
    expirations: [],
    strikes: [],
  };
}

export const SecDefOptParameter: MessageFns<SecDefOptParameter> = {
  encode(message: SecDefOptParameter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.exchange !== undefined) {
      writer.uint32(18).string(message.exchange);
    }
    if (message.underlyingConId !== undefined) {
      writer.uint32(24).int32(message.underlyingConId);
    }
    if (message.tradingClass !== undefined) {
      writer.uint32(34).string(message.tradingClass);
    }
    if (message.multiplier !== undefined) {
      writer.uint32(42).string(message.multiplier);
    }
    for (const v of message.expirations) {
      writer.uint32(50).string(v!);
    }
    writer.uint32(58).fork();
    for (const v of message.strikes) {
      writer.double(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SecDefOptParameter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSecDefOptParameter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.exchange = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.underlyingConId = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.tradingClass = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.multiplier = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.expirations.push(reader.string());
          continue;
        }
        case 7: {
          if (tag === 57) {
            message.strikes.push(reader.double());

            continue;
          }

          if (tag === 58) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.strikes.push(reader.double());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SecDefOptParameter {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      exchange: isSet(object.exchange) ? globalThis.String(object.exchange) : undefined,
      underlyingConId: isSet(object.underlyingConId) ? globalThis.Number(object.underlyingConId) : undefined,
      tradingClass: isSet(object.tradingClass) ? globalThis.String(object.tradingClass) : undefined,
      multiplier: isSet(object.multiplier) ? globalThis.String(object.multiplier) : undefined,
      expirations: globalThis.Array.isArray(object?.expirations)
        ? object.expirations.map((e: any) => globalThis.String(e))
        : [],
      strikes: globalThis.Array.isArray(object?.strikes) ? object.strikes.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: SecDefOptParameter): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.exchange !== undefined) {
      obj.exchange = message.exchange;
    }
    if (message.underlyingConId !== undefined) {
      obj.underlyingConId = Math.round(message.underlyingConId);
    }
    if (message.tradingClass !== undefined) {
      obj.tradingClass = message.tradingClass;
    }
    if (message.multiplier !== undefined) {
      obj.multiplier = message.multiplier;
    }
    if (message.expirations?.length) {
      obj.expirations = message.expirations;
    }
    if (message.strikes?.length) {
      obj.strikes = message.strikes;
    }
    return obj;
  },

  create(base?: DeepPartial<SecDefOptParameter>): SecDefOptParameter {
    return SecDefOptParameter.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SecDefOptParameter>): SecDefOptParameter {
    const message = createBaseSecDefOptParameter();
    message.reqId = object.reqId ?? undefined;
    message.exchange = object.exchange ?? undefined;
    message.underlyingConId = object.underlyingConId ?? undefined;
    message.tradingClass = object.tradingClass ?? undefined;
    message.multiplier = object.multiplier ?? undefined;
    message.expirations = object.expirations?.map((e) => e) || [];
    message.strikes = object.strikes?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
