// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: SmartComponent.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface SmartComponent {
  bitNumber?: number | undefined;
  exchange?: string | undefined;
  exchangeLetter?: string | undefined;
}

function createBaseSmartComponent(): SmartComponent {
  return { bitNumber: undefined, exchange: undefined, exchangeLetter: undefined };
}

export const SmartComponent: MessageFns<SmartComponent> = {
  encode(message: SmartComponent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bitNumber !== undefined) {
      writer.uint32(8).int32(message.bitNumber);
    }
    if (message.exchange !== undefined) {
      writer.uint32(18).string(message.exchange);
    }
    if (message.exchangeLetter !== undefined) {
      writer.uint32(26).string(message.exchangeLetter);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SmartComponent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSmartComponent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.bitNumber = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.exchange = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.exchangeLetter = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SmartComponent {
    return {
      bitNumber: isSet(object.bitNumber) ? globalThis.Number(object.bitNumber) : undefined,
      exchange: isSet(object.exchange) ? globalThis.String(object.exchange) : undefined,
      exchangeLetter: isSet(object.exchangeLetter) ? globalThis.String(object.exchangeLetter) : undefined,
    };
  },

  toJSON(message: SmartComponent): unknown {
    const obj: any = {};
    if (message.bitNumber !== undefined) {
      obj.bitNumber = Math.round(message.bitNumber);
    }
    if (message.exchange !== undefined) {
      obj.exchange = message.exchange;
    }
    if (message.exchangeLetter !== undefined) {
      obj.exchangeLetter = message.exchangeLetter;
    }
    return obj;
  },

  create(base?: DeepPartial<SmartComponent>): SmartComponent {
    return SmartComponent.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SmartComponent>): SmartComponent {
    const message = createBaseSmartComponent();
    message.bitNumber = object.bitNumber ?? undefined;
    message.exchange = object.exchange ?? undefined;
    message.exchangeLetter = object.exchangeLetter ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
