// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: SoftDollarTiersRequest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface SoftDollarTiersRequest {
  reqId?: number | undefined;
}

function createBaseSoftDollarTiersRequest(): SoftDollarTiersRequest {
  return { reqId: undefined };
}

export const SoftDollarTiersRequest: MessageFns<SoftDollarTiersRequest> = {
  encode(message: SoftDollarTiersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SoftDollarTiersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSoftDollarTiersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SoftDollarTiersRequest {
    return { reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined };
  },

  toJSON(message: SoftDollarTiersRequest): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    return obj;
  },

  create(base?: DeepPartial<SoftDollarTiersRequest>): SoftDollarTiersRequest {
    return SoftDollarTiersRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SoftDollarTiersRequest>): SoftDollarTiersRequest {
    const message = createBaseSoftDollarTiersRequest();
    message.reqId = object.reqId ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
