// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: TickAttribLast.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface TickAttribLast {
  pastLimit?: boolean | undefined;
  unreported?: boolean | undefined;
}

function createBaseTickAttribLast(): TickAttribLast {
  return { pastLimit: undefined, unreported: undefined };
}

export const TickAttribLast: MessageFns<TickAttribLast> = {
  encode(message: TickAttribLast, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pastLimit !== undefined) {
      writer.uint32(8).bool(message.pastLimit);
    }
    if (message.unreported !== undefined) {
      writer.uint32(16).bool(message.unreported);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TickAttribLast {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTickAttribLast();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pastLimit = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.unreported = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TickAttribLast {
    return {
      pastLimit: isSet(object.pastLimit) ? globalThis.Boolean(object.pastLimit) : undefined,
      unreported: isSet(object.unreported) ? globalThis.Boolean(object.unreported) : undefined,
    };
  },

  toJSON(message: TickAttribLast): unknown {
    const obj: any = {};
    if (message.pastLimit !== undefined) {
      obj.pastLimit = message.pastLimit;
    }
    if (message.unreported !== undefined) {
      obj.unreported = message.unreported;
    }
    return obj;
  },

  create(base?: DeepPartial<TickAttribLast>): TickAttribLast {
    return TickAttribLast.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TickAttribLast>): TickAttribLast {
    const message = createBaseTickAttribLast();
    message.pastLimit = object.pastLimit ?? undefined;
    message.unreported = object.unreported ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
