// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: TickAttribBidAsk.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface TickAttribBidAsk {
  bidPastLow?: boolean | undefined;
  askPastHigh?: boolean | undefined;
}

function createBaseTickAttribBidAsk(): TickAttribBidAsk {
  return { bidPastLow: undefined, askPastHigh: undefined };
}

export const TickAttribBidAsk: MessageFns<TickAttribBidAsk> = {
  encode(message: TickAttribBidAsk, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bidPastLow !== undefined) {
      writer.uint32(8).bool(message.bidPastLow);
    }
    if (message.askPastHigh !== undefined) {
      writer.uint32(16).bool(message.askPastHigh);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TickAttribBidAsk {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTickAttribBidAsk();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.bidPastLow = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.askPastHigh = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TickAttribBidAsk {
    return {
      bidPastLow: isSet(object.bidPastLow) ? globalThis.Boolean(object.bidPastLow) : undefined,
      askPastHigh: isSet(object.askPastHigh) ? globalThis.Boolean(object.askPastHigh) : undefined,
    };
  },

  toJSON(message: TickAttribBidAsk): unknown {
    const obj: any = {};
    if (message.bidPastLow !== undefined) {
      obj.bidPastLow = message.bidPastLow;
    }
    if (message.askPastHigh !== undefined) {
      obj.askPastHigh = message.askPastHigh;
    }
    return obj;
  },

  create(base?: DeepPartial<TickAttribBidAsk>): TickAttribBidAsk {
    return TickAttribBidAsk.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TickAttribBidAsk>): TickAttribBidAsk {
    const message = createBaseTickAttribBidAsk();
    message.bidPastLow = object.bidPastLow ?? undefined;
    message.askPastHigh = object.askPastHigh ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
