// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: TickSize.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface TickSize {
  reqId?: number | undefined;
  tickType?: number | undefined;
  size?: string | undefined;
}

function createBaseTickSize(): TickSize {
  return { reqId: undefined, tickType: undefined, size: undefined };
}

export const TickSize: MessageFns<TickSize> = {
  encode(message: TickSize, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.tickType !== undefined) {
      writer.uint32(16).int32(message.tickType);
    }
    if (message.size !== undefined) {
      writer.uint32(26).string(message.size);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TickSize {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTickSize();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.tickType = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.size = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TickSize {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      tickType: isSet(object.tickType) ? globalThis.Number(object.tickType) : undefined,
      size: isSet(object.size) ? globalThis.String(object.size) : undefined,
    };
  },

  toJSON(message: TickSize): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.tickType !== undefined) {
      obj.tickType = Math.round(message.tickType);
    }
    if (message.size !== undefined) {
      obj.size = message.size;
    }
    return obj;
  },

  create(base?: DeepPartial<TickSize>): TickSize {
    return TickSize.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TickSize>): TickSize {
    const message = createBaseTickSize();
    message.reqId = object.reqId ?? undefined;
    message.tickType = object.tickType ?? undefined;
    message.size = object.size ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
