// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: TickByTickData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { HistoricalTick } from "./HistoricalTick";
import { HistoricalTickBidAsk } from "./HistoricalTickBidAsk";
import { HistoricalTickLast } from "./HistoricalTickLast";

export const protobufPackage = "protobuf";

export interface TickByTickData {
  reqId?: number | undefined;
  tickType?: number | undefined;
  historicalTickLast?: HistoricalTickLast | undefined;
  historicalTickBidAsk?: HistoricalTickBidAsk | undefined;
  historicalTickMidPoint?: HistoricalTick | undefined;
}

function createBaseTickByTickData(): TickByTickData {
  return {
    reqId: undefined,
    tickType: undefined,
    historicalTickLast: undefined,
    historicalTickBidAsk: undefined,
    historicalTickMidPoint: undefined,
  };
}

export const TickByTickData: MessageFns<TickByTickData> = {
  encode(message: TickByTickData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.tickType !== undefined) {
      writer.uint32(16).int32(message.tickType);
    }
    if (message.historicalTickLast !== undefined) {
      HistoricalTickLast.encode(message.historicalTickLast, writer.uint32(26).fork()).join();
    }
    if (message.historicalTickBidAsk !== undefined) {
      HistoricalTickBidAsk.encode(message.historicalTickBidAsk, writer.uint32(34).fork()).join();
    }
    if (message.historicalTickMidPoint !== undefined) {
      HistoricalTick.encode(message.historicalTickMidPoint, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TickByTickData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTickByTickData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.tickType = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.historicalTickLast = HistoricalTickLast.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.historicalTickBidAsk = HistoricalTickBidAsk.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.historicalTickMidPoint = HistoricalTick.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TickByTickData {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      tickType: isSet(object.tickType) ? globalThis.Number(object.tickType) : undefined,
      historicalTickLast: isSet(object.historicalTickLast)
        ? HistoricalTickLast.fromJSON(object.historicalTickLast)
        : undefined,
      historicalTickBidAsk: isSet(object.historicalTickBidAsk)
        ? HistoricalTickBidAsk.fromJSON(object.historicalTickBidAsk)
        : undefined,
      historicalTickMidPoint: isSet(object.historicalTickMidPoint)
        ? HistoricalTick.fromJSON(object.historicalTickMidPoint)
        : undefined,
    };
  },

  toJSON(message: TickByTickData): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.tickType !== undefined) {
      obj.tickType = Math.round(message.tickType);
    }
    if (message.historicalTickLast !== undefined) {
      obj.historicalTickLast = HistoricalTickLast.toJSON(message.historicalTickLast);
    }
    if (message.historicalTickBidAsk !== undefined) {
      obj.historicalTickBidAsk = HistoricalTickBidAsk.toJSON(message.historicalTickBidAsk);
    }
    if (message.historicalTickMidPoint !== undefined) {
      obj.historicalTickMidPoint = HistoricalTick.toJSON(message.historicalTickMidPoint);
    }
    return obj;
  },

  create(base?: DeepPartial<TickByTickData>): TickByTickData {
    return TickByTickData.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TickByTickData>): TickByTickData {
    const message = createBaseTickByTickData();
    message.reqId = object.reqId ?? undefined;
    message.tickType = object.tickType ?? undefined;
    message.historicalTickLast = (object.historicalTickLast !== undefined && object.historicalTickLast !== null)
      ? HistoricalTickLast.fromPartial(object.historicalTickLast)
      : undefined;
    message.historicalTickBidAsk = (object.historicalTickBidAsk !== undefined && object.historicalTickBidAsk !== null)
      ? HistoricalTickBidAsk.fromPartial(object.historicalTickBidAsk)
      : undefined;
    message.historicalTickMidPoint =
      (object.historicalTickMidPoint !== undefined && object.historicalTickMidPoint !== null)
        ? HistoricalTick.fromPartial(object.historicalTickMidPoint)
        : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
