// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: VerifyCompleted.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface VerifyCompleted {
  isSuccessful?: boolean | undefined;
  errorText?: string | undefined;
}

function createBaseVerifyCompleted(): VerifyCompleted {
  return { isSuccessful: undefined, errorText: undefined };
}

export const VerifyCompleted: MessageFns<VerifyCompleted> = {
  encode(message: VerifyCompleted, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isSuccessful !== undefined) {
      writer.uint32(8).bool(message.isSuccessful);
    }
    if (message.errorText !== undefined) {
      writer.uint32(18).string(message.errorText);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyCompleted {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerifyCompleted();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isSuccessful = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.errorText = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VerifyCompleted {
    return {
      isSuccessful: isSet(object.isSuccessful) ? globalThis.Boolean(object.isSuccessful) : undefined,
      errorText: isSet(object.errorText) ? globalThis.String(object.errorText) : undefined,
    };
  },

  toJSON(message: VerifyCompleted): unknown {
    const obj: any = {};
    if (message.isSuccessful !== undefined) {
      obj.isSuccessful = message.isSuccessful;
    }
    if (message.errorText !== undefined) {
      obj.errorText = message.errorText;
    }
    return obj;
  },

  create(base?: DeepPartial<VerifyCompleted>): VerifyCompleted {
    return VerifyCompleted.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<VerifyCompleted>): VerifyCompleted {
    const message = createBaseVerifyCompleted();
    message.isSuccessful = object.isSuccessful ?? undefined;
    message.errorText = object.errorText ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
