// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: WshMetaData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface WshMetaData {
  reqId?: number | undefined;
  dataJson?: string | undefined;
}

function createBaseWshMetaData(): WshMetaData {
  return { reqId: undefined, dataJson: undefined };
}

export const WshMetaData: MessageFns<WshMetaData> = {
  encode(message: WshMetaData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reqId !== undefined) {
      writer.uint32(8).int32(message.reqId);
    }
    if (message.dataJson !== undefined) {
      writer.uint32(18).string(message.dataJson);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WshMetaData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWshMetaData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reqId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.dataJson = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WshMetaData {
    return {
      reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
      dataJson: isSet(object.dataJson) ? globalThis.String(object.dataJson) : undefined,
    };
  },

  toJSON(message: WshMetaData): unknown {
    const obj: any = {};
    if (message.reqId !== undefined) {
      obj.reqId = Math.round(message.reqId);
    }
    if (message.dataJson !== undefined) {
      obj.dataJson = message.dataJson;
    }
    return obj;
  },

  create(base?: DeepPartial<WshMetaData>): WshMetaData {
    return WshMetaData.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WshMetaData>): WshMetaData {
    const message = createBaseWshMetaData();
    message.reqId = object.reqId ?? undefined;
    message.dataJson = object.dataJson ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
